baseURL = 'https://newenglandhedgehogs.com/'
languageCode = 'en-us'
title = 'New England Hedgehogs'

# Custom Settings

enableGitInfo = true

# Novela settings
theme = "hugo-theme-novela"

paginate = 6

[social]
twitter = "https://twitter.com/HamorHollow"
instagram = "https://www.instagram.com/ChippokeTheTravelingHedgehog/"
youtube = "https://www.youtube.com/user/HamorHollow"
facebook = "https://www.facebook.com/HamorHollow/"
dribbble = "https://hedgehog.gifts/"

[taxonomies]
author = "authors"

# Inline image dimensions: 1888x855
